Improve CD workflow

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -17,6 +17,9 @@ permissions:
   packages: write
   contents: read
 
+env:
+  REGISTRY: ghcr.io
+
 jobs:
   OracleLinux:
     name: OracleLinux
@@ -53,7 +56,7 @@ jobs:
             echo "build=true" >> $GITHUB_OUTPUT
             exit 0
           else
-            if ! docker pull ${{github.repository}}:${{matrix.version}} ; then
+            if ! docker pull "${{env.REGISTRY}}/${{github.repository}}:${{matrix.version}}" ; then
               echo "::warning::Rebuild ${{matrix.version}} (reason: new image)"
               echo "build=true" >> $GITHUB_OUTPUT
               exit 0
@@ -61,7 +64,7 @@ jobs:
 
             check_command=""
 
-            case "${{ matrix.version }}" in
+            case "${{matrix.version}}" in
               "7")      check_command="yum check-update" ;;
               "7-slim") check_command="yum check-update" ;;
               "8")      check_command="dnf check-update" ;;
@@ -71,7 +74,7 @@ jobs:
               *)        exit 1 ;;
             esac
 
-            if ! docker run --rm ${{github.repository}}:${{ matrix.version }} $check_command ; then
+            if ! docker run --rm "${{env.REGISTRY}}/${{github.repository}}:${{matrix.version}}" $check_command ; then
               echo "::warning::Rebuild ${{matrix.version}} (reason: packages update)"
               echo "build=true" >> $GITHUB_OUTPUT
               exit 0
@@ -81,11 +84,16 @@ jobs:
           echo "::endgroup::"
 
           echo -e "::group::\033[34mChecking for rebuilt base image…\033[0m"
+          echo "Pulling oraclelinux:${{matrix.version}} from registry…"
+          echo ""
 
-          docker pull oraclelinux:${{matrix.version}}
+          if ! docker pull "oraclelinux:${{matrix.version}}" ; then
+            echo "::error::Can't pull image oraclelinux:${{matrix.version}}"
+            exit 1
+          fi
 
           orig_dig=$(docker inspect "oraclelinux:${{matrix.version}}" | jq -r '.[0].RootFS.Layers[0]')
-          our_dig=$(docker inspect "${{github.repository}}:${{matrix.version}}" | jq -r '.[0].RootFS.Layers[0]')
+          our_dig=$(docker inspect "${{env.REGISTRY}}/${{github.repository}}:${{matrix.version}}" | jq -r '.[0].RootFS.Layers[0]')
 
           echo ""
           echo "Original: ${orig_dig}"
@@ -123,12 +131,12 @@ jobs:
       - name: Show info about images
         uses: essentialkaos/docker-info-action@v1
         with:
-          image: ${{github.repository}}:${{matrix.version}}
+          image: ${{env.REGISTRY}}/${{github.repository}}:${{matrix.version}}
 
       - name: Scan final image with Trivy
         uses: aquasecurity/trivy-action@master
         with:
-          image-ref: 'ghcr.io/${{github.repository}}:${{matrix.version}}'
+          image-ref: '${{env.REGISTRY}}/${{github.repository}}:${{matrix.version}}'
           format: 'table'
           ignore-unfixed: true
           severity: 'LOW,MEDIUM,HIGH,CRITICAL'
